# This is a config for E2B sandbox template.
# You can use template ID (ozi6z4u0vm1y4f04ys7a) or template name (codex-nextjs-test) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("codex-nextjs-test") # Sync sandbox
# sandbox = await AsyncSandbox.create("codex-nextjs-test") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('codex-nextjs-test')

team_id = "899123b6-b4ac-4c02-b79c-f88fbf32764b"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "codex-nextjs-test"
template_id = "ozi6z4u0vm1y4f04ys7a"
